apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
        - name: my-nodejs-app
          # The image name will be dynamically set with the build number in Jenkins
          image: "appi12/jeeva:50"  # Replace with the image from Docker Hub, Jenkins will inject the BUILD_NUMBER variable
          ports:
            - containerPort: 3000  # Replace with the port your app listens on
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app-service
  namespace: default
spec:
  selector:
    app: my-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Replace with the port your app listens on
  type: LoadBalancer  # You can change this based on your needs (e.g., ClusterIP)
