apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
      - name: my-nodejs-app
        image: appi12/jeeva:${IMAGE_TAG} # Use IMAGE_TAG from Jenkins pipeline
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: my-nodejs-app

