apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: my-react-app
        image: appi12/jeeva:50 # Ensure this React.js image exists in Docker Hub
        ports:
        - containerPort: 3000
      imagePullSecrets: # Add this if the image is private
      - name: my-dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: my-react-app
